spring.application.name=ecommerce-backend

# MySQL 連線
spring.datasource.url=jdbc:mysql://localhost:3306/my_ecommerce_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin123

# JPA 自動建立/更新表格
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
