spring.application.name=ecommerce-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-215a0347-chengkanghow0715-d43a.h.aivencloud.com:18227/defaultdb?sslmode=REQUIRED&enabledTLSProtocols=TLSv1.2,TLSv1.3&trustServerCertificate=true&useSSL=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_hQiWGDnR-BH-wqAltwf}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chengkanghow0715@gmail.com
spring.mail.password=jvozazrusfybzvgz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB